// import type { CalendarEvent } from "./calendar-types"

// function createDate(year: number, month: number, day: number, hour: number, minute: number): Date {
//     return new Date(year, month - 1, day, hour, minute)
// }

// const now = new Date()
// const year = now.getFullYear()
// const month = now.getMonth() + 1

// export const sampleEvents: CalendarEvent[] = [
//     {
//         id: "1",
//         title: "Limpeza dentaria",
//         start: createDate(year, month, 1, 9, 30),
//         end: createDate(year, month, 1, 10, 30),
//         color: "red",
//     },
//     {
//         id: "2",
//         title: "Consulta nutricional",
//         start: createDate(year, month, 1, 11, 0),
//         end: createDate(year, month, 1, 12, 0),
//         color: "orange",
//     },
//     {
//         id: "3",
//         title: "Evento de ciclismo",
//         start: createDate(year, month, 1, 13, 0),
//         end: createDate(year, month, 1, 14, 30),
//         color: "green",
//     },
//     {
//         id: "4",
//         title: "Suporte ao cliente",
//         start: createDate(year, month, 2, 8, 0),
//         end: createDate(year, month, 2, 9, 0),
//         color: "red",
//     },
//     {
//         id: "5",
//         title: "Relacoes com investidores",
//         start: createDate(year, month, 2, 10, 15),
//         end: createDate(year, month, 2, 11, 15),
//         color: "orange",
//     },
//     {
//         id: "6",
//         title: "Consulta juridica",
//         start: createDate(year, month, 2, 10, 30),
//         end: createDate(year, month, 2, 11, 30),
//         color: "green",
//     },
//     {
//         id: "7",
//         title: "Sessao de terapia",
//         start: createDate(year, month, 4, 11, 30),
//         end: createDate(year, month, 4, 12, 30),
//         color: "orange",
//     },
//     {
//         id: "8",
//         title: "Casa aberta escolar",
//         start: createDate(year, month, 5, 11, 45),
//         end: createDate(year, month, 5, 13, 0),
//         color: "teal",
//     },
//     {
//         id: "9",
//         title: "Reuniao de negocios",
//         start: createDate(year, month, 5, 12, 0),
//         end: createDate(year, month, 5, 13, 0),
//         color: "blue",
//     },
//     {
//         id: "10",
//         title: "Standup do time",
//         start: createDate(year, month, 6, 9, 15),
//         end: createDate(year, month, 6, 9, 45),
//         color: "green",
//     },
//     {
//         id: "11",
//         title: "Partida de voo",
//         start: createDate(year, month, 6, 12, 30),
//         end: createDate(year, month, 6, 14, 0),
//         color: "red",
//     },
//     {
//         id: "12",
//         title: "Planejamento de conteudo",
//         start: createDate(year, month, 6, 15, 0),
//         end: createDate(year, month, 6, 16, 0),
//         color: "blue",
//     },
//     {
//         id: "13",
//         title: "Jogo de basquete",
//         start: createDate(year, month, 7, 11, 15),
//         end: createDate(year, month, 7, 12, 30),
//         color: "orange",
//     },
//     {
//         id: "14",
//         title: "Viagem de negocios",
//         start: createDate(year, month, 9, 10, 15),
//         end: createDate(year, month, 9, 12, 0),
//         color: "blue",
//     },
//     {
//         id: "15",
//         title: "Standup do time",
//         start: createDate(year, month, 10, 14, 15),
//         end: createDate(year, month, 10, 14, 45),
//         color: "green",
//     },
//     {
//         id: "16",
//         title: "Workshop de arte",
//         start: createDate(year, month, 10, 10, 45),
//         end: createDate(year, month, 10, 12, 0),
//         color: "purple",
//     },
//     {
//         id: "17",
//         title: "Reuniao pais e mestres",
//         start: createDate(year, month, 11, 12, 0),
//         end: createDate(year, month, 11, 13, 0),
//         color: "orange",
//     },
//     {
//         id: "18",
//         title: "Servico religioso",
//         start: createDate(year, month, 12, 10, 15),
//         end: createDate(year, month, 12, 11, 30),
//         color: "red",
//     },
//     {
//         id: "19",
//         title: "Acampamento de fim de semana",
//         start: createDate(year, month, 12, 10, 15),
//         end: createDate(year, month, 12, 18, 0),
//         color: "teal",
//     },
//     {
//         id: "20",
//         title: "Standup do time",
//         start: createDate(year, month, 16, 11, 0),
//         end: createDate(year, month, 16, 11, 30),
//         color: "blue",
//     },
//     {
//         id: "21",
//         title: "Sessao de fotografia",
//         start: createDate(year, month, 16, 13, 0),
//         end: createDate(year, month, 16, 14, 0),
//         color: "purple",
//     },
//     {
//         id: "22",
//         title: "Aula de yoga",
//         start: createDate(year, month, 15, 11, 15),
//         end: createDate(year, month, 15, 12, 15),
//         color: "teal",
//     },
//     {
//         id: "23",
//         title: "Consulta juridica",
//         start: createDate(year, month, 17, 9, 15),
//         end: createDate(year, month, 17, 10, 15),
//         color: "blue",
//     },
//     {
//         id: "24",
//         title: "Planejamento de conteudo",
//         start: createDate(year, month, 17, 12, 0),
//         end: createDate(year, month, 17, 13, 0),
//         color: "purple",
//     },
//     {
//         id: "25",
//         title: "Revisao de orcamento",
//         start: createDate(year, month, 18, 9, 45),
//         end: createDate(year, month, 18, 10, 45),
//         color: "orange",
//     },
//     {
//         id: "26",
//         title: "Reuniao familiar",
//         start: createDate(year, month, 18, 10, 30),
//         end: createDate(year, month, 18, 12, 0),
//         color: "green",
//     },
//     {
//         id: "27",
//         title: "Relacoes com investidores",
//         start: createDate(year, month, 19, 8, 45),
//         end: createDate(year, month, 19, 10, 0),
//         color: "orange",
//     },
//     {
//         id: "28",
//         title: "Consulta juridica",
//         start: createDate(year, month, 19, 16, 28),
//         end: createDate(year, month, 19, 17, 28),
//         color: "green",
//     },
//     {
//         id: "29",
//         title: "Aula de yoga",
//         start: createDate(year, month, 14, 10, 15),
//         end: createDate(year, month, 14, 11, 15),
//         color: "red",
//     },
//     {
//         id: "30",
//         title: "Evento de ciclismo",
//         start: createDate(year, month, 20, 9, 15),
//         end: createDate(year, month, 20, 10, 30),
//         color: "red",
//     },
//     {
//         id: "31",
//         title: "Orientacao de estagio",
//         start: createDate(year, month, 20, 9, 15),
//         end: createDate(year, month, 20, 10, 30),
//         color: "purple",
//     },
//     {
//         id: "32",
//         title: "Check-in hotel",
//         start: createDate(year, month, 21, 14, 45),
//         end: createDate(year, month, 21, 15, 45),
//         color: "teal",
//     },
//     {
//         id: "33",
//         title: "Evento de ciclismo",
//         start: createDate(year, month, 23, 10, 30),
//         end: createDate(year, month, 23, 11, 30),
//         color: "blue",
//     },
//     {
//         id: "34",
//         title: "Auditoria de ciberseguranca",
//         start: createDate(year, month, 23, 12, 15),
//         end: createDate(year, month, 23, 13, 30),
//         color: "red",
//     },
//     {
//         id: "35",
//         title: "Backup de dados",
//         start: createDate(year, month, 24, 8, 30),
//         end: createDate(year, month, 24, 9, 30),
//         color: "teal",
//     },
//     {
//         id: "36",
//         title: "Partida de futebol",
//         start: createDate(year, month, 24, 14, 30),
//         end: createDate(year, month, 24, 16, 0),
//         color: "blue",
//     },
//     {
//         id: "37",
//         title: "Suporte ao cliente",
//         start: createDate(year, month, 28, 12, 45),
//         end: createDate(year, month, 28, 13, 45),
//         color: "teal",
//     },
//     {
//         id: "38",
//         title: "Reuniao do conselho",
//         start: createDate(year, month, 30, 9, 0),
//         end: createDate(year, month, 30, 10, 0),
//         color: "red",
//     },
//     {
//         id: "39",
//         title: "Avaliacao de desempenho",
//         start: createDate(year, month, 30, 9, 15),
//         end: createDate(year, month, 30, 10, 15),
//         color: "teal",
//     },
//     {
//         id: "40",
//         title: "Planejamento de ferias",
//         start: createDate(year, month, 30, 9, 30),
//         end: createDate(year, month, 30, 10, 30),
//         color: "blue",
//     },
//     {
//         id: "41",
//         title: "Sprint planning",
//         start: createDate(year, month, 3, 9, 0),
//         end: createDate(year, month, 3, 10, 30),
//         color: "blue",
//     },
//     {
//         id: "42",
//         title: "Code review",
//         start: createDate(year, month, 8, 14, 0),
//         end: createDate(year, month, 8, 15, 0),
//         color: "purple",
//     },
//     {
//         id: "43",
//         title: "Retrospectiva",
//         start: createDate(year, month, 10, 16, 0),
//         end: createDate(year, month, 10, 17, 0),
//         color: "teal",
//     },
//     {
//         id: "44",
//         title: "Demo do produto",
//         start: createDate(year, month, 25, 10, 0),
//         end: createDate(year, month, 25, 11, 0),
//         color: "green",
//     },
// ]
