services:
  frontend:
    container_name: tasks-frontend
    build: .
    working_dir: /app
    env_file:
      - .env
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
